### ISSUE TITLE
Console UI fails to load for example `mystreams` service

### ISSUE THREAD

**Issue by dcberg** [IBM/cloud-operators#32]
I followed the instructions to create a service and binding for Streams (e.g., `mystreams` service instance). The service and binding are created. When I click on the `mystreams` service from the OCP cluster console I get an empty page which you cannot go back.

Looking in the web browser console I see the following error.

`WebSocket connection to 'wss://console.dan-rhos10-f0a5715bb2873122b708ede2bf765701-0001.us-east.containers.appdomain.cloud/api/kubernetes/apis/ibmcloud.ibm.com/v1alpha1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Dmystreams&x-csrf-token=XXXXXXXXXXXX' failed: WebSocket is closed before the connection is established.
o.destroy @ index.tsx:52'

**Comment by vazirim** [comment]
@dcberg could you share the yaml you used?

**Comment by vazirim** [comment]
@dcberg I just tried the `mystreams` example we have in our samples.
It seems to provision fine, but I cannot access the web console. This isn't actually a problem with the cloud operator but the service itself. I asked on Slack to see if the service is down (in the past they have fixed stuff for us), cc'ed you there

**Comment by pdettori** [comment]
I was able to reproduce the issue with a different service (watson translator) so this is not related to provisioning IBM Streaming Analytics. However, the issue seems to happen only with the console in 3.11, and it works fine in OpenShift 4. Will continue to explore to see what is affecting this.

**Comment by pdettori** [comment]
so, I tested also with a Binding and the 3.11 console works fine for that. I have a strong suspicion at this point that there might be an issue with the 3.11 console due to the resource name 'Service' (it happens only with that). It is possible that the console is not considering the api group and version and is trying to find a native Kubernetes Service, so it hangs there. This does not happen with OpenShift 4, where the issue is likely resolved. Not sure there is a solution for this with the 3.11 console.

**Comment by pdettori** [comment]
Following the steps in https://github.ibm.com/seed/olm/tree/master/pocs/openshift-ibmcloud#installing-upstream-openshift-console I have pointed a OpenShift 4 console to my ROKS cluster and verified that the issue does not happen there. 

The conclusion is that this is a specific issue for the 3.11 console, where operator support was just experimental and it is likely due to the 3.11 console support not handling correctly the a resource with name Service (overlapping with the native Service in Kubernetes).

To point a v4 console to the existing 3.11 cluster, you may try to run the console locally in docker, as long as your `oc` command is setup:

```
endpoint=$(kubectl config view -o json | jq '{myctx: .["current-context"], ctxs: .contexts[], clusters: .clusters[]}' | jq 'select(.myctx == .ctxs.name)' | jq 'select(.ctxs.context.cluster ==  .clusters.name)' | jq '.clusters.cluster.server' -r)
token=$(kubectl config view -o json | jq '{myctx: .["current-context"], ctxs: .contexts[], clusters: .clusters[], users: .users[]}' | jq 'select(.myctx == .ctxs.name)' | jq 'select(.ctxs.context.user ==  .users.name)' | jq '.users.user.token' -r)

args="--net=host"
if [[ $OSTYPE == darwin* ]]; then
  args="-p 9000:9000"
fi

docker run --name console -d $args \
  -e BRIDGE_USER_AUTH="disabled" \
  -e BRIDGE_K8S_MODE="off-cluster" \
  -e BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT=$endpoint \
  -e BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS=true \
  -e BRIDGE_K8S_AUTH="bearer-token" \
  -e BRIDGE_K8S_AUTH_BEARER_TOKEN=$token\
  quay.io/openshift/origin-console:latest
```
On OSX, you should be able to access to OpenShift 4 console at http://localhost:9000

**Comment by pdettori** [comment]
View with the v4 console pointed to my ROKS instance:
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/6678093/61418103-65b79880-a8c7-11e9-99fb-d5c99d057869.png">

**Comment by pdettori** [comment]
Closing, since this issue cannot is caused by a OpenShift 3.11 UI issue.
